// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:string):Promise<void>;

export function GetHomeDir():Promise<string>;

export function GetParentDirectory(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function JoinPath(arg1:string,arg2:string):Promise<string>;

export function ListDirectory(arg1:string,arg2:boolean):Promise<Array<main.FileEntry>>;

export function MoveEntry(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function RenameEntry(arg1:string,arg2:string,arg3:string):Promise<void>;
