// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetHomeDir():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListDirectory(arg1:string):Promise<Array<main.FileEntry>>;
