// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetParentDirectory(arg1) {
  return window['go']['main']['App']['GetParentDirectory'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function JoinPath(arg1, arg2) {
  return window['go']['main']['App']['JoinPath'](arg1, arg2);
}

export function ListDirectory(arg1, arg2) {
  return window['go']['main']['App']['ListDirectory'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}
